// <auto-generated />
using System;
using GymRoutineGenerator.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymRoutineGenerator.Data.Migrations
{
    [DbContext(typeof(GymRoutineContext))]
    [Migration("20250923164155_AddUserProfileEntities")]
    partial class AddUserProfileEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpanishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryMuscleGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpanishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyLevel");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("Name");

                    b.HasIndex("ParentExerciseId");

                    b.HasIndex("PrimaryMuscleGroupId");

                    b.HasIndex("SpanishName");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.ExerciseImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePosition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ExerciseImages");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.ExerciseSecondaryMuscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroupId");

                    b.HasIndex("ExerciseId", "MuscleGroupId")
                        .IsUnique();

                    b.ToTable("ExerciseSecondaryMuscles");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpanishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.UserEquipmentPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("UserProfileId", "EquipmentTypeId")
                        .IsUnique();

                    b.ToTable("UserEquipmentPreferences");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.UserMuscleGroupPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmphasisLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroupId");

                    b.HasIndex("UserProfileId", "MuscleGroupId")
                        .IsUnique();

                    b.ToTable("UserMuscleGroupPreferences");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.UserPhysicalLimitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomRestrictions")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("LimitationType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserPhysicalLimitations");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainingDaysPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.Exercise", b =>
                {
                    b.HasOne("GymRoutineGenerator.Data.Entities.EquipmentType", "EquipmentType")
                        .WithMany("Exercises")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymRoutineGenerator.Data.Entities.Exercise", "ParentExercise")
                        .WithMany("ChildExercises")
                        .HasForeignKey("ParentExerciseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GymRoutineGenerator.Data.Entities.MuscleGroup", "PrimaryMuscleGroup")
                        .WithMany("PrimaryMuscleExercises")
                        .HasForeignKey("PrimaryMuscleGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentType");

                    b.Navigation("ParentExercise");

                    b.Navigation("PrimaryMuscleGroup");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.ExerciseImage", b =>
                {
                    b.HasOne("GymRoutineGenerator.Data.Entities.Exercise", "Exercise")
                        .WithMany("Images")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.ExerciseSecondaryMuscle", b =>
                {
                    b.HasOne("GymRoutineGenerator.Data.Entities.Exercise", "Exercise")
                        .WithMany("SecondaryMuscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymRoutineGenerator.Data.Entities.MuscleGroup", "MuscleGroup")
                        .WithMany("SecondaryMuscleExercises")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.UserEquipmentPreference", b =>
                {
                    b.HasOne("GymRoutineGenerator.Data.Entities.EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymRoutineGenerator.Data.Entities.UserProfile", "UserProfile")
                        .WithMany("EquipmentPreferences")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentType");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.UserMuscleGroupPreference", b =>
                {
                    b.HasOne("GymRoutineGenerator.Data.Entities.MuscleGroup", "MuscleGroup")
                        .WithMany()
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymRoutineGenerator.Data.Entities.UserProfile", "UserProfile")
                        .WithMany("MuscleGroupPreferences")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuscleGroup");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.UserPhysicalLimitation", b =>
                {
                    b.HasOne("GymRoutineGenerator.Data.Entities.UserProfile", "UserProfile")
                        .WithMany("PhysicalLimitations")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.EquipmentType", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.Exercise", b =>
                {
                    b.Navigation("ChildExercises");

                    b.Navigation("Images");

                    b.Navigation("SecondaryMuscles");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.MuscleGroup", b =>
                {
                    b.Navigation("PrimaryMuscleExercises");

                    b.Navigation("SecondaryMuscleExercises");
                });

            modelBuilder.Entity("GymRoutineGenerator.Data.Entities.UserProfile", b =>
                {
                    b.Navigation("EquipmentPreferences");

                    b.Navigation("MuscleGroupPreferences");

                    b.Navigation("PhysicalLimitations");
                });
#pragma warning restore 612, 618
        }
    }
}
